# config for yelp dataset
# exp info
exp_type: once # once or 5_round
log_filename: UUB_m1_0.0

# data info
dt: epinions # scale of data
data_dir: data/dt/exp_split/1/ # data dir for this exp, dt will be replaced by the dt string in the running time
train_filename: ratings.txt
test_filename: test.txt
meta_graphs: ['UUB_m1_0.0'] # meta-graphs used in 
topK: 500 # topK neighbours saved in meta-graph based similarity computation, used to specify the corresponding user and item latent features.

# Model parameters
K: 10 # rank of FM
F: 10 # rank for MF to generate latent features
initial: 1e-3 # initial factor multiply by initial values of parameters
bias: 0 # bias used in the FM model
reg_W: 0.5 # regularization weight for W
reg_P: 0.5 # regularization weight for P
reg_Q: 0.5 # regularization weight for Q
max_iters: 10000 # max iterations in the training process
ln: 1000 # max steps in line search
eps: 1e-8 # stopping criteria
eta: 1e-7 # initial step-size
solver: nmAPG
bias_eta: 1e-7 # fixed stepsize for bias
theta: 10 # theta for the non-convex regularizer in LSP
nnl: 0 # the values for lambda in nuclear norm
