# config for yelp dataset
# exp info
exp_type: once # once or 5_round
log_filename: ratings_only_fm_fmhpk_vs_anova.log

# data info
dt: yelp-50k # scale of data
data_dir: data/dt/exp_split/2/ # data dir for this exp, dt will be replaced by the dt string in the running time
train_filename: ratings_train_2.txt
test_filename: ratings_test_2.txt
meta_graphs: ['ratings_only'] # meta-graphs used in 
topK: 500 # topK neighbours saved in meta-graph based similarity computation, used to specify the corresponding user and item latent features.

# Model parameters
K: 50 # rank of FM
F: 10 # rank for MF to generate latent features
initial: 1e-4 # initial factor multiply by initial values of parameters
bias: 0 # bias used in the FM model
reg_W: 10 # regularization weight for W
reg_P: 10 # regularization weight for P
reg_Q: 10 # regularization weight for Q
max_iters: 1000 # max iterations in the training process
ln: 200 # max steps in line search
eps: 1e-8 # stopping criteria
eta: 1e-7 # initial step-size
